unique_name: products
object_type: dimension
label: products
hierarchies:
  - unique_name: Color-Size
    label: Color-Size
    levels:
      - unique_name: Color
      - unique_name: Size
      - unique_name: Product ID
  - unique_name: Product Line
    label: Product Line
    levels:
      - unique_name: Product Category
      - unique_name: Subcategory
      - unique_name: Product
level_attributes:
  - unique_name: Color
    label: Color
    contains_unique_names: false
    dataset: vwproducts
    is_unique_key: false
    key_columns:
      - color
    name_column: color
  - unique_name: Size
    label: Size
    contains_unique_names: false
    dataset: vwproducts
    is_unique_key: false
    key_columns:
      - size
    name_column: size
  - unique_name: Product ID
    label: Product ID
    contains_unique_names: false
    dataset: vwproducts
    is_hidden: true
    is_unique_key: false
    key_columns:
      - productid
    name_column: productid
  - unique_name: Product Category
    label: Product Category
    contains_unique_names: false
    dataset: vwproductcategories
    is_unique_key: false
    key_columns:
      - productcategoryid
    name_column: productcategoryname
  - unique_name: Subcategory
    label: Subcategory
    contains_unique_names: false
    dataset: vwproductsubcategories
    is_unique_key: false
    key_columns:
      - productsubcategoryid
    name_column: productsubcategoryname
  - unique_name: Product
    label: Product
    contains_unique_names: false
    dataset: vwproducts
    is_unique_key: false
    key_columns:
      - productid
    name_column: name
relationships:
  - unique_name: >-
      vwproductsubcategories_productsubcategoryid_to_subcategories_productsubcategoryname
    from:
      dataset: vwproductsubcategories
      hierarchy: Product Line
      join_columns:
        - productsubcategoryid
      level: Subcategory
    to:
      dimension: subcategories
      level: productsubcategoryname
    type: embedded
  - unique_name: vwproductcategories_productcategoryid_to_categories_productcategoryname
    from:
      dataset: vwproductcategories
      hierarchy: Product Line
      join_columns:
        - productcategoryid
      level: Product Category
    to:
      dimension: categories
      level: productcategoryname
    type: embedded
  - unique_name: vwproducts_productsubcategoryid_to_subcategories_productsubcategoryname
    from:
      dataset: vwproducts
      hierarchy: Color-Size
      join_columns:
        - productsubcategoryid
      level: Color
    to:
      dimension: subcategories
      level: productsubcategoryname
    type: embedded
  - unique_name: vwproductsubcategories_productcategoryid_to_categories_productcategoryname
    from:
      dataset: vwproductsubcategories
      hierarchy: Product Line
      join_columns:
        - productcategoryid
      level: Subcategory
    to:
      dimension: categories
      level: productcategoryname
    type: embedded
type: standard
