unique_name: products
object_type: dimension
label: products
hierarchies:
  - unique_name: Products
    label: Products
    levels:
      - unique_name: Category
      - unique_name: Subcategory
      - unique_name: Product
  - unique_name: Color-Size
    label: Color-Size
    levels:
      - unique_name: Color
      - unique_name: Size
      - unique_name: Product ID
level_attributes:
  - unique_name: Category
    label: Category
    contains_unique_names: false
    dataset: vwproductcategories
    is_unique_key: false
    key_columns:
      - productcategoryid
    name_column: productcategoryname
  - unique_name: Subcategory
    label: Subcategory
    contains_unique_names: false
    dataset: vwproductsubcategories
    is_unique_key: false
    key_columns:
      - productsubcategoryid
    name_column: productsubcategoryname
  - unique_name: Product
    label: Product
    contains_unique_names: false
    dataset: vwproducts
    is_unique_key: false
    key_columns:
      - productid
    name_column: name
  - unique_name: Color
    label: Color
    contains_unique_names: false
    dataset: vwproducts
    is_unique_key: false
    key_columns:
      - color
    name_column: color
  - unique_name: Size
    label: Size
    contains_unique_names: false
    dataset: vwproducts
    is_unique_key: false
    key_columns:
      - size
    name_column: size
  - unique_name: Product ID
    label: Product ID
    contains_unique_names: false
    dataset: vwproducts
    is_hidden: true
    is_unique_key: false
    key_columns:
      - productid
    name_column: productid
relationships:
  - unique_name: >-
      vwproductsubcategories_productcategoryid_to_product-categories.yml_Category
    from:
      dataset: vwproductsubcategories
      hierarchy: Products
      join_columns:
        - productcategoryid
      level: Subcategory
    to:
      dimension: product-categories.yml
      level: Category
    type: embedded
  - unique_name: vwproductcategories_productcategoryid_to_product-subcategories_Subcategory
    from:
      dataset: vwproductcategories
      hierarchy: Products
      join_columns:
        - productcategoryid
      level: Category
    to:
      dimension: product-subcategories
      level: Subcategory
    type: embedded
type: standard
