unique_name: product-subcategories
object_type: dimension
label: product-subcategories
hierarchies:
  - unique_name: Product Subcategories
    label: Product Subcategories
    levels:
      - unique_name: Subcategory
level_attributes:
  - unique_name: Subcategory
    label: Subcategory
    description: '`'
    contains_unique_names: false
    dataset: vwproductsubcategories
    is_unique_key: false
    key_columns:
      - productsubcategoryid
    name_column: productsubcategoryname
type: standard
