unique_name: products
object_type: dimension
label: products
hierarchies:
  - unique_name: Color-Size
    label: Color-Size
    levels:
      - unique_name: Color
      - unique_name: Size
      - unique_name: Product ID
level_attributes:
  - unique_name: Color
    label: Color
    contains_unique_names: false
    dataset: vwproducts
    is_unique_key: false
    key_columns:
      - color
    name_column: color
  - unique_name: Size
    label: Size
    contains_unique_names: false
    dataset: vwproducts
    is_unique_key: false
    key_columns:
      - size
    name_column: size
  - unique_name: Product ID
    label: Product ID
    contains_unique_names: false
    dataset: vwproducts
    is_hidden: true
    is_unique_key: false
    key_columns:
      - productid
    name_column: productid
relationships: []
type: standard
